name: Condition
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }} #ワークフロー実行IDで分岐

  success:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0 #処理ステータスが0なので成功ステータス
      - run: echo "Hello"
        if: ${{ success() }}

  failure:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1 #処理ステータスが0ではないためエラーが発生
      - run: echo "Hello"
        if: ${{ failure() }}
