services:
    # PHPアプリケーションサービス
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - db

    # Nginxウェブサーバーサービス
    web:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app

    # MySQLデータベースサービス
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
