name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.action }}"
      - run: echo "${{ github.action_path }}"
      - run: echo "${ github.action_ref }}"
      - run: echo "${{ github.action_repository }}"
      - run: echo "${{ github.action_status }}"
      - run: echo "${{ github.actor }}"
      - run: echo "${{ github.actor_id }}"
      - run: echo "${{ github.api_url }}"
      - run: echo "${{ github.base_ref }}"
      - run: echo "${{ github.env }}"
      - run: echo "${{ github.event }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.event_path }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.ref_name }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.repository_id }}"
      - run: echo "${{ github.repository_owner }}"
      - run: echo "${{ github.run_id }}"
      - run: echo "${{ github.run_number }}"
      - run: echo "${{ github.secret_source }}"
      - run: echo "${{ github.server_url }}"
      - run: echo "${{ github.sha }}"
      - run: echo "${{ github.triggering_actor }}"
      - run: echo "${{ github.workflow }}"
      - run: echo "${{ github.workspace }}"
