# name: Contexts
# on: push
# jobs:
#   print:
#     runs-on: ubuntu-latest
#     env:
#       ACTION: ${{ github.action }}
#       ACTION_PATH: ${{ github.action_path }}
#       ACTION_REF: ${{ github.action_ref }}
#       ACTION_REPOSITORY: ${{ github.action_repository }}
#       ACTION_STATUS: ${{ github.action_status }}
#     steps:
#       - run: echo "${{ env.ACTION }}"
#       - run: echo "${{ env.ACTION_PATH }}"
#       - run: echo "${{ env.ACTION_REF }}"
#       - run: echo "${{ env.ACTION_REPOSITORY }}"
#       - run: echo "${{ env.ACTION_STATUS }}"
