name: Debug log
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::This is a debug log" #デバッグログ有効化時にのみ出力
      - run: echo "::error::This is an error" #errorレベルのアノテーション
      - run: echo "::warning::THis is a warning" #warningレベルのアノテーション
      - run: echo "::notice::This is a notice" #noticeレベルのアノテーション
