name: Environments
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    environment: test
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"
