name: Old
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #ステップ１：　チェックアウト
      - uses: shivammathur/setup-php@v2 #ステップ2：　古いPHPバージョンで言語セットアップ
        with:
          php-version: "7.0"
