name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ runner.name }}"
      - run: echo "${{ runner.os }}"
      - run: echo "${{ runner.arch }}"
      - run: echo "${{ runner.temp }}"
      - run: echo "${{ runner.tool_cache }}"
      - run: echo "${{ runner.debug }}"
