name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #ステップ１：　チェックアウト
      - uses: shivammathur/setup-php@v2 #ステップ2：　言語セットアップ
        with:
          php-version: "8.3"
      - run: cp .env.example .env # ステップ3：Laravelの初期設定envファイルのコピー
      - run: composer install # ステップ4: 依存関係のインストール
      - run: php artisan key:generate # ステップ5: Laravelのアプリケーションキーの生成
      - run: ./vendor/bin/phpunit #ステップ6：　テストの実行
